# Generated by Django 3.1.2 on 2020-11-13 01:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Описание отсутствует",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="announcements",
                                      verbose_name="Фотография животного"),
                ),
                (
                    "announcement_type",
                    models.IntegerField(
                        choices=[(1, "Потеряно"), (2, "Найдено")],
                        default=1,
                        verbose_name="Тип объявления",
                    ),
                ),
                (
                    "animal_type",
                    models.IntegerField(
                        choices=[(1, "Собака"), (2, "Кошка"), (3, "Другое")],
                        default=1,
                        verbose_name="Тип животного",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Место пропажи/находки",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True,
                                      null=True,
                                      verbose_name="Широта"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True,
                                      null=True,
                                      verbose_name="Долгота"),
                ),
                (
                    "contact_phone_number",
                    models.CharField(max_length=12,
                                     verbose_name="Контактный телефон"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Изменено"),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
