# Generated by Django 3.1.2 on 2020-11-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_announcement_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Описание"
            ),
        ),
    ]
