# Generated by Django 3.1.3 on 2021-01-02 22:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0010_auto_20201126_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="address",
            field=models.CharField(
                max_length=1000, verbose_name="Место пропажи или находки"
            ),
        ),
    ]
