# Generated by Django 3.1.2 on 2021-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='announcements/%Y/%m/%d/', verbose_name='Фотография животного')),
                ('announcement_type', models.IntegerField(choices=[(1, 'Потеряно'), (2, 'Найдено')], verbose_name='Тип объявления')),
                ('animal_type', models.IntegerField(choices=[(1, 'Собаки'), (2, 'Кошки'), (3, 'Иные')], verbose_name='Тип животного')),
                ('address', models.CharField(max_length=1000, verbose_name='Место пропажи или находки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('contact_phone_number', models.CharField(max_length=12, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-created_at',),
            },
        ),
    ]
