# Generated by Django 3.1.2 on 2021-10-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetconfirmationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='PasswordResetConfirmationCode',
        ),
    ]
