# Generated by Django 3.1.2 on 2021-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(
                upload_to='announcements/%Y/%m/%d/', verbose_name='Фотография животного'),
        ),
    ]
