# Generated by Django 3.1.2 on 2020-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20201113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
