# Generated by Django 3.1.2 on 2020-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20201115_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
    ]
